#!/bin/bash

origin_url=`git config --get remote.origin.url`

if [[ "$origin_url" =~ "git@github.com:ProductMadness" ]] || [[ "$origin_url" =~ "git@github.com:jbrotons" ]] ; then
  ssh_key=klashuk_itran_rsa
else
  ssh_key=klashuk_gmail_rsa
fi

/usr/bin/env ssh -q -2 -o "StrictHostKeyChecking=yes" -i "$HOME/.ssh/$ssh_key" $1 $2
