#!/bin/bash
if [[ $PWD =~ "work/madness" ]] ; then
  git_email=kirill.lashuk@productmadness.com
else
  git_email=kirill.lashuk@gmail.com
fi

GIT_AUTHOR_EMAIL=$git_email GIT_COMMITTER_EMAIL=$git_email /usr/bin/git $@
